### ISSUE TITLE
[RelayCommand] implementation leaks subscribers

### ISSUE THREAD

**Issue by albyrock87** [CommunityToolkit/dotnet#1017]
### Describe the bug

The `RelayCommand` is leaking the command's subscriber when command's lifespan is bigger than the subscribers (i.e. singleton command with a `Button` subscriber within a pop-able page).

### Steps to reproduce

Check out this repository's branch: https://github.com/albyrock87/maui-shell-issues/tree/relay-command-leak

- Start the iOS app
- Tap on `Open sub page`
- Press back
- See the message saying that the button's reference is still alive

Now comment `[RelayCommand]` and uncomment the standard `ICommand` implementation above.
Repeat the steps and notice how the reference is gone.

https://github.com/albyrock87/maui-shell-issues/blob/relay-command-leak/BarPage.xaml.cs#L12-L31

### Expected behavior

GC should be able to collect the command subscriber as it does with `Command`.

### IDE and version

Rider

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [x] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.3.2

### Additional context

![Image](https://github.com/user-attachments/assets/d72cc3ec-0db1-4d89-8edb-786438339a78)

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
Where is that `Command` implementation from?
Are you able to provide a minimal repro? Like, a unit test.

**Comment by albyrock87** [comment]
That's the standard `Command` implementation that everyone uses when they don't use the community toolkit mvvm.

It's even used in the documentation:
https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/commanding?view=net-maui-9.0#basic-commanding

The repo I've attached is very minimal, but yeah it's not a unit test.

I'll try to find the time to provide a unit test.

**Comment by Sergio0694** [comment]
If it's [this one](https://github.com/dotnet/maui/blob/b4795133f86c79ef73d9e08a5bc4f277c1813320/src/Controls/src/Core/Command.cs#L64) this seems by design. That command implementation is using (for some reason) a weak even manager. We don't support this in the MVVM Toolkit. Also worth noting that the implementation of that weak even manager is really bad for trimming (one of the reasons we're not using it). In your case, the real issue seems to just be the fact you're storing the page into a static. Having commands with strong references is usually fine otherwise. And if you want to share viewmodels then you'd need manual cleanup either way.

**Comment by pictos** [comment]
Hello, just jump here to add some context for future adventures that may land here. The Maui Command leaking is a .NET MAUI that I'm working on (probably the fix will be just in 2025, because of holidays).

Here is the PR (related issue attached to it) for reference

- https://github.com/dotnet/maui/pull/26044

**Comment by albyrock87** [comment]
@Sergio0694 why would the weak event manager be a bad thing for trimming or in general a bad thing?

Why would the MAUI team do something so wrong on a fundamental piece of the architecture?

MAUI has a lot of weak references all around to avoid leaks, especially on iOS, and still trimming is working fine.

That said, I think the behavior should be consistent, or anyway it should be very clear and documented whether the command implementation holds strong reference or not so that developers and third party library authors can take appropriate countermeasures.

For example, DevExpress today refused my memleak bug report because with `Command` there's no leak, and `Command` represents the standard on MAUI.

**Comment by albyrock87** [comment]
@Sergio0694 I think I get your point now: the community toolkit could use a `WeakEventManager` but that also means that any kind of `event` should use it, even `PropertyChanged`.

That brings everything into a pattern that leads to worse performance.

So it should be up to the developers to unsubscribe properly when the event lives longer than the subscriber.

We should probably create a documentation page on MAUI side to explain how to deal with these situations.
