### ISSUE TITLE
[Feature] Add support for InvalidCastException to ThrowHelpers

### ISSUE THREAD

**Issue by Arvtesh** [CommunityToolkit/dotnet#115]
Seems weird that [ThrowHelpers](https://github.com/CommunityToolkit/dotnet/blob/main/CommunityToolkit.Diagnostics/ThrowHelper.cs) do not implement helpers for all of the standard exceptions. At least there seems to be no methods for [InvalidCastException](https://docs.microsoft.com/en-us/dotnet/api/system.invalidcastexception).

**Comment by Sergio0694** [comment]
This is by design, as `InvalidCastException` is not an exception that should ever be thrown explicitly by user code. The only case where that is documented to be the case is in custom types implementing `IConvertible`, which is an interface with pretty questionable design (read: pretty bad), and even then it's an extremely niche case. We don't want to incentivize using this exception type in user code by adding APIs for this, as this exception should just never be used 🙂
