### ISSUE TITLE
Guard - Option to not throw. Pass in delegate perhaps?

### ISSUE THREAD

**Issue by jamesmontemagno** [CommunityToolkit/dotnet#144]
One thing that would be nice is to have `Guard` work similar to how it does in Swift where it will execute some code and allow the developers to return.

Not exactly sure how this would work though being able to escape out of the method.

![image](https://user-images.githubusercontent.com/1676321/158068357-4dc00900-7cd2-438b-abc1-cb21e415da70.png)

only option i see is to do something like:

```csharp
if(Guard.IsNotNull(array, nameof(array)))
{
     //do stuff here and optionally return
}
```

**Comment by Sergio0694** [comment]
Hey James! I'm a bit confused by this proposal and how it'd fit in with the way the `Guard` APIs work.

Since they're all just throwing an exception (by design) when a check fails, you can't really have them return a `bool` (as they'd basically only ever return `true`, or not return at all). It seems to me your sample snippet would basically expect a completely different API than `Guard`, that just does the same validation but without throwing? In that case though, I'm confused as to why you're also passing the parameter name there, what would you expect that method to do with it?

As for passing a delegate to be invoked in case of failure but before the exception is thrown, that's unfortunately not doable, as it'd essentially break one of the premises of these APIs - being fast. Passing a delegate would require callers to always allocate them (as they're evaluated before invoking the `Guard` API regardless of the outcome of the check), which would also mean allocating a closure if any state is captured as well. This would significantly hurt performance (and memory usage) unconditionally, so even if the faulting path is not actually taken. I've written a detailed explanation of the codegen aspect of the `Guard` APIs [here](https://docs.microsoft.com/en-us/windows/communitytoolkit/developer-tools/throwhelper#technical-details) if you're interested - that should hopefully make it clear why passing a `Delegate` here is not really doable 🙂

**Comment by jamesmontemagno** [comment]
Gotcha, yeah that makes sense. I was just thinking this morning as they are the same name as in swift maybe could be something similar, but this feels like a language feature most likely.

**Comment by Sergio0694** [comment]
Yeah, something like that would likely need language support 🙂

The inspiration for `Guard` is to basically end up with something similar to what Midori had, ie:

```csharp
public int Read(char[] buffer, int index, int count)
    requires buffer != null
    requires index >= 0
    requires count >= 0
    requires buffer.Length - index >= count
{
    // Code here...
}
```

Of course, we don't have that fancy `requires` in C# (nor the static analysis that the contracts being part of the method signature provided), but I feel like this still lets us get to something that's conceptually similar, at least functionally:

```csharp
public int Read(char[] buffer, int index, int count)
{
    Guard.IsTrue(buffer != null);
    Guard.IsTrue(index >= 0);
    Guard.IsTrue(count >= 0);
    Guard.IsTrue(buffer.Length - index >= count);

    // Code here...
}
```

Or, rewriting that with a more "guard-style" approach:

```csharp
public int Read(char[] buffer, int index, int count)
{
    Guard.IsNotNull(buffer);
    Guard.IsGreaterThanOrEqualTo(index, 0);
    Guard.IsGreaterThanOrEqualTo(count, 0);
    Guard.IsTrue(buffer.Length - index >= count);

    // Code here...
}
```

The whole design is to just list requirements and then "fail-fast", without users needing to care about branches or anything.
