### ISSUE TITLE
AsyncRelayCommand wpf problem

### ISSUE THREAD

**Issue by kronic** [CommunityToolkit/dotnet#149]
CommunityToolkit.Mvvm 8.0.0-preview2
Wpf after the first execution of an asynchronous command, the button is unavailable
[TestProject](https://disk.yandex.ru/d/jT5Qf6s2zSubGg)

**Comment by Sergio0694** [comment]
Hey @kronic! This was a known issue with Preview2, which has already been fixed by https://github.com/CommunityToolkit/dotnet/pull/139.
Could you try out the latest preview version and confirm whether that fixed the issue for you?
You can use the latest version you see at this feed: `https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-MainLatest/nuget/v3/index.json`.

**Comment by kronic** [comment]
Hello @Sergio0694 yes everything works

**Comment by Sergio0694** [comment]
Sweet, glad to hear that's fixed, thank you! 😄
