### ISSUE TITLE
AllowConcurrentExecutions broke after updating from preview 1 to 2

### ISSUE THREAD

**Issue by Tederean** [CommunityToolkit/dotnet#150]
The removed canExecute check in Execute function led to a side effect where an asynchronous command is executed concurrently despite AllowConcurrentExecutions is set to false.

https://github.com/CommunityToolkit/dotnet/pull/131 https://github.com/CommunityToolkit/dotnet/commit/7a4eccbc10fa3b85808f89903331a3643b9724fc

Using Xamarin.Forms 5.0.0.2337 and 8.0.0-preview1 everthing works fine. Tap on a button should open a new page, no matter how fast I tap. With same Xamarin.Forms version and 8.0.0-preview2 test page get's created twice if i do a fast double tap.

```
		[ICommand(AllowConcurrentExecutions = false)]
		private async Task Test()
		{
			var page = new TestPage();

			await Application.Current.MainPage.Navigation.PushAsync(page);
			await Task.Delay(200);
		}
```

Why this was removed? Because it was done on purpose - how can i prevent this odd behaviour in my code?

**Comment by Sergio0694** [comment]
Hi @Tederean! 👋
You're correct, this change was intentional, and the reason is that the previous implementation wasn't following the [ICommand](https://docs.microsoft.com/dotnet/api/system.windows.input.icommand) contract properly. You can see there that `Execute` is meant to just execute the logic of the command, without additional checks. It is whoever's calling `Execute` that is responsible for calling `CanExecute` first to verify whether the command can be executed. So now we're doing just that. Note that this should still work fine with the button not being able to be called multiple times, as the UI framework should always be `CanExecute` and update the visual state whenever `CanExecuteChanged` is raised.

For instance, from our [sample app](https://github.com/CommunityToolkit/MVVM-Samples) (tweaking the async relay command page a bit):

```xml
<StackPanel Spacing="8">
    <TextBlock>
        <Run Text="Counter:" />
        <Run Text="{x:Bind ViewModel.Counter, Mode=OneWay}" />
    </TextBlock>
    <Button Command="{x:Bind ViewModel.DownloadTextCommand}" Content="Click me!" />
    <muxc:ProgressBar
        Width="80"
        HorizontalAlignment="Left"
        IsIndeterminate="{x:Bind ViewModel.DownloadTextCommand.IsRunning, Mode=OneWay}" />
</StackPanel>
```
```csharp
[ObservableProperty]
private int counter;

[ICommand]
private async Task DownloadTextAsync()
{
    Counter++;
    await Task.Delay(3000);
}
```

And you can see the result:

![ApplicationFrameHost_6wVh05o0Yb](https://user-images.githubusercontent.com/10199417/158178434-3b9e96b2-6a87-4497-b2eb-d24ec539d857.gif)

You can see the button is automatically disabled when the command is executing.
Can you not repro this on Xamarin with the latest preview version?
Make sure to grab the latest version from our main feed (`https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-MainLatest/nuget/v3/index.json`).

**P.S.** small note, we changed the default in Preview2 to be `allowConcurrentExecutions = false`, so no need to set it anymore 🙂

**Comment by Tederean** [comment]
Hi, thank you for your quick response and comprehensive answer.

There seems to be a problem with the Xamarin TapGestureRecognizer as a standard button doesn't create our problem as I just found out. A button that is deactivated cannot trigger the problem, since it does not even get through to the 'CanExecute' check.

The issue has probably been settled with that.

**Comment by crwsolutions** [comment]
I just started to exlore this package. Maybe this is related. But I have xamarin page with a <RefreshView Command="{Binding LoadDataCommand}" This Command is only fired once unless I add the attribute: [ICommand(AllowConcurrentExecutions = true)]. So without this attribute I go to this page, data is loaded. go out (clear the model) and go back again and then nothing happens.

**Comment by Sergio0694** [comment]
Hey @crwsolutions! So there's two things here:

- Preview2 switched the default execution mode of async commands to block concurrent executions.
- I also accidentally broke the non concurrent async commands in Preview2, so they don't notify when the task completes 😅

I suspect the second point might be what's causing the issue you're seeing. Could you try using the latest build from our preview feed from main (https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-MainLatest/nuget/v3/index.json) and seeing if that solves the issue for you? 🙂

**Comment by crwsolutions** [comment]
Yes, that solves the issue.
