### ISSUE TITLE
Check (a partner API to Guard)

### ISSUE THREAD

**Issue by Avid29** [CommunityToolkit/dotnet#176]
### Overview

This is very similar to #144, except instead of being part of Guard, Check is its own API.

Check would contain an equivalent method for each Guard method that returns a simple true or false instead of throwing

### API breakdown

A null check would look like this

```cs
public static class Check
{
    /// <summary>
    /// Checks that the input value is <see langword="null"/>.
    /// </summary>
    /// <typeparam name="T">The type of reference value type being tested.</typeparam>
    /// <param name="value">The input value to test.</param>
    /// <returns>True if the value is null, False otherwise.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static bool IsNull<T>(T? value)
    {
        return value is null;
    }
}
```

Which is extremely similar to the null guard's

```cs
public static class Guard
{
    /// <summary>
    /// Asserts that the input value is <see langword="null"/>.
    /// </summary>
    /// <typeparam name="T">The type of reference value type being tested.</typeparam>
    /// <param name="value">The input value to test.</param>
    /// <param name="name">The name of the input parameter being tested.</param>
    /// <exception cref="ArgumentException">Thrown if <paramref name="value"/> is not <see langword="null"/>.</exception>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void IsNull<T>(T? value, [CallerArgumentExpression("value")] string name = "")
    {
        if (value is null)
        {
            return;
        }

        ThrowHelper.ThrowArgumentExceptionForIsNull(value, name);
    }
}
```

In practice such a simple check would not be used alone, but having a check equivalent for every guard would provide consistency and the more elaborate checks are useful.

### Usage example

```cs
public struct UniformKernel
{
  private double _min;
  private double _max;
  
  public double Weight(double value)
  {
    return Check.IsBetween(value, _min, _max) ? 1 : 0;
  }
}
```

In more elaborate contexts it might just return a sentinel value early

### Breaking change?

No

### Alternatives

This is just candy. The alternative is to check these simple conditions where needed without a helper method.

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by Arlodotexe** [comment]
Will need feedback from @Sergio0694 on this 🙂

**Comment by Arlodotexe** [comment]
@Nirmal4G Guard and ThrowHelper serve two different puposes.

**Comment by Nirmal4G** [comment]
Is there any place where we don't check but throw directly?

**Comment by Sergio0694** [comment]
Alright, sorry for the delay reviewing this. I don't like this idea and I don't think it's worth it 🥲

The `Guard` APIs have a very specific use case where it makes sense to encapsulate the check + throw logic, but I don't think the same applies for just the check logic, given it'd add a considerable amount of new public APIs and binary size to the package, and most importantly yet another way which is not idiomatic to do some checks. As in, APIs such as `IsNotNull` have no reason to exist on their own, when you can do `is not null`. Or, an API like `IsTrue` makes no sense, or an API like `IsCompleted` (instead of literally just accessing a property on a task, etc.). I'm not seeing enough value to justify this, nor a real reason why this should be added even ignoring the additional complexity. If you don't want to have the check + throw logic encapsulated, you should simply inline that same check (which is pretty much always trivial) and then use `ThrowHelper`.
