### ISSUE TITLE
New methods that assert that value matches/satisfies [Or not] a pattern/predicate.

### ISSUE THREAD

**Issue by mabroukmahdhi** [CommunityToolkit/dotnet#196]
### Overview

The feature will contain following methods:

1. **Match** : Asserts that a regular expression is matched.
2. **NotMatch** : Asserts that a regular expression is not matched.
3. **Match\<T>** : Asserts that a predicate is  satisfied.
4. **NotMatch\<T>** : Asserts that a predicate is not satisfied.

### API breakdown

```csharp
namespace CommunityToolkit.Diagnostics;

public static partial class Guard
{
   public static void Match<T>(T value, Expression<Func<T, bool>> predicate, [CallerArgumentExpression("value")] string name = "");

   public static void NotMatch<T>(T value, Expression<Func<T, bool>> predicate, [CallerArgumentExpression("value")] string name = "");

   public static void Match(string value, string regexPattern, [CallerArgumentExpression("value")] string name = "");

   public static void NotMatch(string value, string regexPattern, [CallerArgumentExpression("value")] string name = "");
}
````

### Usage example

```csharp
public void Insert(User user)
{
    Guard.Match(user, u => u.Id == 0, nameof(some_name));
   
}

public void Update(User user)
{
    Guard.NotMatch(user, u => u.Id == 0, nameof(some_name));
   
}

public void SendFreeSms(User user, string message)
{
    //Sms only to a german number
    Guard.Match(user.Phone, "^\+49([0-9]*)", nameof(some_name));
    
}

public void SendSms(User user, string message)
{
    //Sms to all countries but german
    Guard.NotMatch(user.Phone, "^\+49([0-9]*)", nameof(some_name));
    
}

```

### Breaking change?

No

### Alternatives

Nothing

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by mabroukmahdhi** [comment]
Hey changes are done.. i am waiting for issue approval

**Comment by Sergio0694** [comment]
I have a few issues with the proposed APIs, let's go through them one by one:

```csharp
public static partial class Guard
{
   public static void Match<T>(T value, Expression<Func<T, bool>> predicate, [CallerArgumentExpression("value")] string name = "");
}
```

Let's leave the naming aside (should be `IsMatch`, not `Match`). The `predicate` parameter being an `Expression<T>` is not really necessary here: it being an expression doesn't add anything of value to the API, and makes the API unnecessarily expensive to use (each caller would have to create a whole expression every time). Unless, this was done specifically so that the API could then explore the expression to produce an error message. I can understand that, but still, way too expensive. But even ignoring this (ie. let's suppose this took a `Func<T, bool>`, this would directly go against one of the core principles of the `Guard` APIs: being fast. An API like this would either force callers to allocate a delegate (potentially with the additional pit of failure of the closure allocation if they're not careful), or even in the best case scenario still go through a delegate invocation. All other `Guard` APIs are instead specifically designed to be easily inlineable and result in the best performance possible. Also, I'm not really seeing the value in this, from the proposed example:

```csharp
// Proposal
Guard.Match(user, u => u.Id == 0, nameof(some_name));

// This can already be done
Guard.IsEqual(user.Id, 0);
```

This would result in `"user.Id"` being passed as parameter name, which would still give the same information for messages.

```csharp
public static partial class Guard
{
   public static void Match(string value, string regexPattern, [CallerArgumentExpression("value")] string name = "");

   public static void NotMatch(string value, string regexPattern, [CallerArgumentExpression("value")] string name = "");
}
```

This has a similar issue than before, in that it pushed developers towards an inefficient pattern. Especially now that we're about to get source generated regex, this would instead cause the implementation to fallback to interpreted/dynamic regex, which is not ideal. Additionally, I'd argue the API has a not so expressive name, especially along with the other proposed overloads.

Just like with the previous API, this can also already be done, more efficiently, with existing APIs:

```csharp
// Proposal
Guard.Match(user.Phone, "^\+49([0-9]*)", nameof(some_name));

// This can already be done
Guard.IsTrue(PhoneRegex.IsMatch(user.Phone), nameof(user), $"The {nameof(user.Phone)} property must be a phone number (was {user.Phone}).");
```

This leverages the new interpolated string handler, which causes the call to be lowered like so:

```csharp
bool value = PhoneRegex.IsMatch(user.Phone);
Guard.IsTrueInterpolatedStringHandler handler = new(..., ..., value, out bool shouldAppend);
if (shouldAppend)
{
    handler.AppendLiteral("The Phone property must be a phone number (was ");
    handler.AppendFormatted(user.Phone);
    handler.AppendLiteral(").");
}
Guard.IsTrue(value, "user", ref handler);
```

Which allows the happy path (when no exception is thrown) to remain zero-allocation and as fast as possible 🙂
