### ISSUE TITLE
Auto-generation of ObservableObject/ObservableProperty fails with build error: namespace already contains definition

### ISSUE THREAD

**Issue by skanvk15** [CommunityToolkit/dotnet#286]
I am creating a new Win UI3 app and adding a model derived from ObservableObject like this

```
using Microsoft.Toolkit.Mvvm.ComponentModel;

namespace App2.Model
{
    public class User4 : ObservableObject
    {
        [ObservableProperty]
        private int Id;

        [ObservableProperty]
        private string Name;
    }
}
```

This fails build with error:
Error	CS0101	The namespace 'App2.Model' already contains a definition for 'User4'	

When I double click on the error, it takes me to the auto-generated code.

**Comment by Sergio0694** [comment]
You're missing the `partial` modifier on your class.
If you hover on it or read the exception message, you should see an error about "missing partial modifier" as well 🙂

**Comment by skanvk15** [comment]
Thanks that was it! Though I did not see anything indicating missing partial modifier when I tried to hover. Would be good to add that directly in the error if possible. The reason is that the code generation only happens (or at least the error only happens) when certain attributes are added (e.g. [ObservableProperty]). Its possible as the code is edited that these may get introduced later and all of a sudden this error appears. This recommendation to extend the error message is lower priority.

**Comment by mrlacey** [comment]
While it might not be possible to add to the errors seen above, what about adding an analyzer to detect that the class inherits from `Microsoft.Toolkit.Mvvm.ComponentModel.ObservableObject` but is not partial?

**Comment by mrlacey** [comment]
> You don't really need an analyzer

No, you don't _need_ an analyzer, but my thinking was to try and warn about the issue as early as possible, rather than wait for compilation to fail.

> we could very well emit the additional diagnostics right from the source generator if we wanted (a source generator is an analyzer after all)

Yes, great.
Better to check that the output of the source generator isn't going to be invalid, rather than allow the compiler to complain about what's generated.

> The reason why we're not doing that is that Roslyn should already produce the correct error message, given the type conflict is an error it's already detecting. 

The compiler is producing a correct error message, but it can never no the reason why there are two types with the same name in the source code. 
Surely it's better to verify the assumption implicit in the use of this source generator: that it's adding to a partial class. This way the source generator can give a precise description of what's wrong and details of how to fix it.
Yes, a generic solution might be simpler in the long run but adding the check now could help people sooner than waiting for a future compiler change.
A suitable generic fix might be treating all source instances of a class as partial if one of them is marked this way. But there are potentially lots of ways of addressing this that may or may not require a change in the error message.
If you can add a link here to any related issue you raise with the Roslyn folks, I'd be interested in following that discussion. (I can't find any issue when searching their repo.)

**Comment by Sergio0694** [comment]
I should also say that I _do_ get this diagnostic already:

![](https://user-images.githubusercontent.com/10199417/171190888-96cc8017-61bd-41d7-b487-e57dcb2a0497.png)

So I'm not really sure I understand what else is needed here.

**Comment by mrlacey** [comment]
> I should also say that I _do_ get this diagnostic already:
> 
> ![](https://user-images.githubusercontent.com/10199417/171190888-96cc8017-61bd-41d7-b487-e57dcb2a0497.png)
> 
> So I'm not really sure I understand what else is needed here.

Well, that was kind of what I was suggesting. It's there already. I'm not sure there's anything more to discuss here. Let's let the discussion on the Roslyn repo take over.
