### ISSUE TITLE
when I press the button it stays as caught

### ISSUE THREAD

**Issue by Javier118** [CommunityToolkit/dotnet#293]
when I press the button it is caught as frozen when Click on the button but if in the Xaml code I remove the Click the button works normal.
`<AppBarButton x:Name="BtAccept" Icon="Accept" Click="BTAccept_Click"/>` 
the button in code-behind carries async and code for database

**Comment by Sergio0694** [comment]
Can you share more info on your setup? Are you using Preview2? This seems very similar to #137, which has been fixed already 🙂

**Comment by Javier118** [comment]
ok .

**Comment by Sergio0694** [comment]
That's not what I meant, and also I've asked you to share more info, otherwise we can't do anything. What version are you using? Have you tried using 8.0.0-Preview3 to see if the issue is fixed?

**Comment by Javier118** [comment]
I have  this version [. https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.TemplateStudioForUWP](url)

**Comment by Sergio0694** [comment]
Windows Template Studio is still using version 7.1.2 of the Toolkit, which is unsupported. This issue has been fixed already on 8.0.0, so it should work for you if you update to the latest preview version 🙂

FYI @mrlacey

**Comment by mrlacey** [comment]
> Windows Template Studio is still using version 7.1.2 of the Toolkit, which is unsupported. This issue has been fixed already on 8.0.0, so it should work for you if you update to the latest preview version 🙂
> 
> FYI @mrlacey

Template Studio has tried to avoid using preview versions of any packages because it creates lots of issues with updates, support, and any potential breaking changes made to a package while it's in preview.

@Javier118  Please can you confirm which package this refers to? I assume this issue refers to `Microsoft.Toolkit.MVVM` but it would be good to have this explicitly stated so I'm not making any incorrect assumptions.

@Sergio0694 what does it mean that "version 7.1.2 of the Toolkit, is unsupported"?
Does this mean it should not be used?
It's still the latest non-preview version available.
Is there an expected/planned release date for the next GA version?

**Comment by Sergio0694** [comment]
> "Template Studio has tried to avoid using preview versions of any packages because it creates lots of issues with updates, support, and any potential breaking changes made to a package while it's in preview."

Yeah no, I know that, the FYI was just for you to see the thread, it wasn't meant to suggest you should do anything 🙂

> "what does it mean that "version 7.1.2 of the Toolkit, is unsupported"? Does this mean it should not be used?"

It can be used, I just mean that there are no plans to update it, so issues that are there but have been fixed in new preview versions will not be backported. There will not be a new servicing update to the 7.x.x branch, is what I mean. As soon as 8.0.0 is out, the whole `Microsoft.Toolkit.*` group of libraries from the .NET Community Toolkit will just be deprecated 😄

> "Is there an expected/planned release date for the next GA version?"

I plan on publishing a Preview 4 soon (next couple days?), and then if nothing pops up I think we should be able to hopefully push 8.0.0 to stable before the end of the month. It's been in preview for a while so I'm confident enough in what we have now.

**Comment by Javier118** [comment]
hello: 
Now, the button works in the App but yesterday it was like frozen.
