### ISSUE TITLE
ObservableProperty duplicates the generated property

### ISSUE THREAD

**Issue by rasotoipc** [CommunityToolkit/dotnet#335]
### Duplicate Generated Property

When I add the [ObservableProperty] to a property, the generated code is duplicated. 

![image](https://user-images.githubusercontent.com/36775149/177788609-b976713c-fae4-4e68-94d4-f197cb818b39.png)

### Steps to reproduce

```text
Added [ObservableProperty] to two properties

1. isBusy
2. title
```

### Expected behavior

The properties auto generated should not duplicate. I should only see one property for each ObservableProperty.

### Screenshots

it seems that the generator is not generating files even though I was able to access them.

![image](https://user-images.githubusercontent.com/36775149/177796594-d3a84a11-4f1b-4a15-88cb-e8c40c4e98f3.png)

_No response_

### IDE and version

VS 2022 Preview

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0.0-preview4

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
I cannot repro this, everything works just fine for me:

![](https://user-images.githubusercontent.com/10199417/177797878-039add3e-b008-4a3b-823a-247b301b3e48.png)

I noticed you're using an iOS target, I wonder if this might be caused by some multi-targeted config. Are you using a MAUI project? Can you share a complete minimal repro we can use?
