### ISSUE TITLE
Source generators are not compatible with Xamarin Forms.

### ISSUE THREAD

**Issue by SittenSpynne** [CommunityToolkit/dotnet#364]
### Describe the bug

In the announcement for version 8, it was said:

> All the available APIs have no dependencies on any specific runtime or framework, so they can be used by all .NET developers. 

However, if I try to use the toolkit in a Xamarin Forms project, I get this compiler warning:

>   CommunityToolkit.Mvvm.targets(41, 5): The MVVM Toolkit source generators have been disabled on the current configuration, as they need Roslyn 4.x in order to work. The MVVM Toolkit will work just fine, but features relying on the source generators will not be available.

If this toolkit is meant to work with all MS frameworks, it should not be relying on Roslyn features that are not supported by all Roslyn frameworks. It will be at least a year before all of our apps can be ported to MAUI, so Xamarin Forms is still extant and relevant. 

### Steps to reproduce

```text
1. I'm using latest VS for Mac 2022 and Rider 2022.2 on MacOS Monterey.
2. I create a new Xamarin Forms project and don't change any defaults.
3. I add the package "CommunityToolkit.Mvvm" version 8.0.0.0.
4. I build the project.
5. I receive the indicated warning.
```

### Expected behavior

I would expect the source generators to work because this toolkit committed to being the reference implementation that works with no external dependencies. 

### IDE and version

VS 2022 Preview, Rider

### IDE version

17.3 build 2089

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0

### Additional context

I feel like this worked in at least one preview version of the toolkit I tried. At one point I almost adopted the preview as part of my Xamarin Forms project, but now I'm glad I didn't. 

### Help us help you

Yes, but only if others can assist. (As in, I have no  clue what a solution could be and maybe my Xamarin project settings could be updated, but keep in mind it also has to work with Xamarin UI Test which has some specific requirements too. But if given a clear solution I don't mind working on it.)

**Comment by Sergio0694** [comment]
> "If this toolkit is meant to work with all MS frameworks, it should not be relying on Roslyn features that are not supported by all Roslyn frameworks. It will be at least a year before all of our apps can be ported to MAUI, so Xamarin Forms is still extant and relevant."

I think there's some confusion here. In blog post, I said:

> "All the available APIs have no dependencies on any specific _runtime_ or _framework_"

This is _true_. The Roslyn dependency is a tooling dependency (ie. the compiler), not a runtime or framework. The two are completely orthogonal. And I never said we'd support older versions of the compiler, because in fact we don't 🙂

That said, this is weird, given you're using VS2022 and Rider, which should have Roslyn 4.x. I suspect the issue might be Xamarin.Forms not using an updated toolset and somehow ending up loading an older version of Roslyn. The only fix for this would be for you to find a way to get it to use Roslyn 4.x, but this is not something we can fix on our end.

Also, for context, only supporting Roslyn 4.x was not a choice for us. The only way would've been to multi-target and ship a non-incremental source generator to use on Roslyn 3.x, but that would've meant:
- Way more maintenance effort for us (we now need to ship a multi-target project with more pipeline complexity etc.)
- Terrible experience for users anyway, because non incremental source generators are inherently slow and very inefficient. So we'd have gotten a lot of reports from people complaining about the MVVM Toolkit making VS extremely slow and laggy for them, which we didn't want.

Hope this helps! 😄

**Comment by SittenSpynne** [comment]
Yes, there's definitely something more to this. I tried on a "cleaner" laptop today and don't get the warning. There must be something funky on my work laptop making it use an older version of Roslyn.

**Comment by SittenSpynne** [comment]
# SOLUTION:

On the machine where this reproduces, both VS for Mac 2019 and VS for Mac 2022 are installed. For whatever reason, Rider had decided to use the MSBuild that VS for Mac 2019 uses. Somehow that seemed to impact VS for Mac 2022 as well. Changing the setting to use the VS for Mac 2022 toolchain solves the issue. (This makes sense, as we're in the bonkers state where VS 2019 is effectively not supported and VS 2022, despite being "in preview" and very rough, is the only VS on Mac receiving feature updates.)

For the sake of anyone who might've searched their way into this, in Rider:

1. Open options/preferences.
2. Click "Build, Execution, Deployment > Toolset and Build"
3. Find the drop-down labled "MSBuild version".
4. Open the drop-down and pick a different version of MSBuild.
    * For me, the WRONG version was in a ".../Visual Studio/8.0/..." directory. The CORRECT version is in ".../Visual Studio/17.0/..." even though they are both listed as the same version of MSBuild.
5. It MAY be a good idea to update the "Mono executable path" field as well, but it didn't seem required for me.

Note this is by default a project-specific setting, you may or may not want to follow the instructions in the dialog to save it for all projects.
