### ISSUE TITLE
Toolkit Doesn't Detect UnSupported C# Version or Doesn't work on C# 8

### ISSUE THREAD

**Issue by AathifMahir** [CommunityToolkit/dotnet#376]
### Describe the bug

Community Toolkit MVVM Doesn't Support C# Version 8 and Does Only Work with C# Version 9 and Above at the time of writing, In this case there's no proper warning or error output that relates to Community Toolkit MVVM on Compilation

### Regression

7.1.2

### Reproducible in sample app?

- [x] This bug can be reproduced in the sample app.

### Steps to reproduce

```text
1. Create Vanilla UWP Project
2. Install Community Toolkit 8.0 using Nuget
3. Compile the App
```

### Expected behavior

Community Toolkit MVVM Should Have Language Barrier to Prevent the Dependency from Installing on C# version 8 since least version of C# that is supported by Community Toolkit MVVM is C# Version 9 at the time of writing or Community Toolkit MVVM Should Support C# version 8

### Screenshots

![Screenshot 2022-08-10 1303041](https://user-images.githubusercontent.com/17165402/184004030-cdbafe44-71a7-4324-b3d3-6e382d6be3dd.png)

### Visual Studio Version

2022

### Visual Studio Build Number

17.3

### Nuget packages

Community Toolkit 8.0

### Help us help you

Yes, but only if others can assist.

**Comment by michael-hawker** [comment]
@AathifMahir there's many community toolkits, so you need to be more specific. But I'm pretty sure you're talking about the MVVM package. I think you and Sergio may have been talking about this on Discord?

There's supposed to be a specific analytic message which instructs the developer about this change, but appears to not be showing up here.

**Comment by Sergio0694** [comment]
I think I forgot to update the generated code in the cached args when I lowered the minimum language version to C# 8. I reckon removing the target-typed `new` expressions from there should be enough, and then we can keep C# 8 as minimum. The check there is already in place, it's just that it's not enough because that generated code accidentally still used C# 9 features.

Should be an easy fix, will take a look in a bit 🙂
I reckon it should be enough to just replace this with an initializer taking the identifier name explicitly:

https://github.com/CommunityToolkit/dotnet/blob/96517eace88d95ec52a881e3e1ed74ea51436b40/CommunityToolkit.Mvvm.SourceGenerators/ComponentModel/ObservablePropertyGenerator.Execute.cs#L979-L983

**Comment by AathifMahir** [comment]
> @AathifMahir there's many community toolkits, so you need to be more specific. But I'm pretty sure you're talking about the MVVM package. I think you and Sergio may have been talking about this on Discord?
> 
> There's supposed to be a specific analytic message which instructs the developer about this change, but appears to not be showing up here.

Took care of it 👍

**Comment by zsolt3991** [comment]
Is vanilla UWP still under support with the new 8.x.x versions of the Mvvm Toolkit? Even C#8 as minimum version would require manually bumping the LanguageVersion of the consuming project, which brings some risks that have to be managed relating to some of the C#8 features, since UWP is normally stuck on 7.3. 
Or should UWP consumers refrain from using the Source Generator based functionalities, since the code generated adheres to the C#8 spec and even this could be subject to change when .Net Core 3.1 is deprecated in November?
