### ISSUE TITLE
MvvM Source Generator doesn't check all the inheritance chain

### ISSUE THREAD

**Issue by pictos** [CommunityToolkit/dotnet#470]
### Describe the bug

I'm using the .NET MAUI and want to use the MVVM SG to create some bindable properties, but when I tried I get first error

```
Error	MVVMTK0019	The field CommunityToolkit.Maui.Sample.TouchPageSample.touchCount cannot be used to generate an observable property, as its containing type doesn't inherit from ObservableObject, nor does it use [ObservableObject] or [INotifyPropertyChanged]
```

![image](https://user-images.githubusercontent.com/20712372/196839716-acc53f84-29e4-4f60-93f4-61d0dfb87c2c.png)

But, when I try to decorate the class with the `INotifyPropertyChanged` attribute I get an error saying the class already implements that interface, as you can see in the image below

![image](https://user-images.githubusercontent.com/20712372/196839862-8f48bbd2-735d-4160-beb7-c830555f94bb.png)

### Steps to reproduce

```text
1. Checkout this [branch](https://github.com/pictos/SGReproOnPages.App)
2. Open the MainPage.xaml.cs file
```

### Expected behavior

The SG works and doesn't see the `MVVMTK0019` error.

### IDE and version

VS 2022

### IDE version

17.3.6

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
This is by design, and can be reproed with this:

```csharp
public class A : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler? PropertyChanged;
}

public partial class B : A
{
    [ObservableProperty]
    private bool someValue;
}
```

The reason this doesn't work is that `[ObservableProperty]` needs additional methods to be present, as those are the ones it relies on in the generated code (eg. `OnPropertyChanged`). In order to be sure they are available and simplify the generator, this requires the containing type to either inherit from `ObservableObject` or to have one of those attributes, which will guarantee those methods are present. In this case instead the base type is implementing `INotifyPropertyChanged` manually. Because of that though, you can't add `[INotifyPropertyChanged]` either, because the type already implements the interface, as the message is saying.

The solution is to change the base type to not implement the interface manually, but to instead inherit from `ObservableObject`, or to be decorated with `[INotifyPropertyChanged]` 🙂

**Comment by pictos** [comment]
@Sergio0694 so if I don't have access to the base type I can't use it? Or is there a workaround?

**Comment by Sergio0694** [comment]
That is correct. This would add a lot of complexity and overhead to the generator, because now in order to generate the property it'd need to traverse the entire hierarchy tree and then all the methods, to try to find whether there is an accessible one with the right signature to notify changes. That gets pretty involved if you also consider things such as internal methods and an assembly having internals visible to another, etc. So for now we just said this is not supported by design 🙂

**Comment by pictos** [comment]
Got it, thanks @Sergio0694 for all explanations❣️
