### ISSUE TITLE
Allow to rename the command through RelayCommand attribute

### ISSUE THREAD

**Issue by bdovaz** [CommunityToolkit/dotnet#537]
### Overview

I have a WPF project that uses a bit complex binding where it expects a command to be called PositiveCommand and NegativeCommand.

The problem is that in my ViewModel I don't want the method to be called Positive() and Negative() because it doesn't reflect in the ViewModel clearly the intent and I would like something along the lines of.

### API breakdown

```csharp
public sealed class RelayCommandAttribute : Attribute
{
    public string? Name { get; set; }
}
```

### Usage example

```csharp
[RelayCommand("Positive")]
private void Create() {
}

[RelayCommand("Negative")]
private void Cancel() {
}
```

### Breaking change?

No

**Comment by Sergio0694** [comment]
This is not something we're thinking of adding, we've deliberately avoided adding a way to configure the name of generated members via string parameters into attributes as that feels very clunky and not really idiomatic in C# 🙂

**Comment by activa** [comment]
> This is not something we're thinking of adding, we've deliberately avoided adding a way to configure the name of generated members via string parameters into attributes as that feels very clunky and not really idiomatic in C# 🙂

I don't understand this reasoning. The only reason why we're not using `[RelayCommand]` in our project is because we can't customize the name of the command property being generated. The reason is that we use a specific naming scheme for methods that are command handlers to differentiate from other methods.

For example:
```
private void Cmd_Save()
{
}
```

When adding the `[RelayCommand]` attribute, the name of the property being generated is `Cmd_SaveCommand` which is a very awkward name.

The effort to add custom command names is very low, so why deliberately reject the idea because it feels clunky to you?
