### ISSUE TITLE
Add filtering functionality to WeakReferenceMessenger 

### ISSUE THREAD

**Issue by msadeh** [CommunityToolkit/dotnet#595]
### Overview

Would be nice to have a mechanism to filter messages. Right now Tokens can be used for 'simple' filtering. For example a requirements for one recipient to receive messages for just for a few Senders with different signature/token but more than one.

Adding a Predicate for filtering will be a great additional functionality.

Thanks!

### API breakdown

```csharp
public void Register<TRecipient, TMessage>(TRecipient recipient, Predicate<TMessage> filter, MessageHandler<TRecipient, TMessage> handler) where TRecipient : class where TMessage : class;
```

### Usage example

```csharp
public void Register<TRecipient, TMessage>(TRecipient recipient, Predicate<TMessage> filter, MessageHandler<TRecipient, TMessage> handler) where TRecipient : class where TMessage : class;
```

### Breaking change?

No

### Alternatives

no

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by Sergio0694** [comment]
This issue is incorrectly stating that this would not be a breaking change, but it would. Adding a new API to an existing interface is both a source and binary breaking change for everyone consuming that interface and/or trying to use that method. Additionally, not sure why you replied "no" to "Alternatives", but it seems like you can in fact achieve this with an extension method, no?

```csharp
public static void Register<TRecipient, TMessage>(this IMessenger messenger, TRecipient recipient, Predicate<TMessage> filter, MessageHandler<TRecipient, TMessage> handler)
    where TRecipient : class
    where TMessage : class
{
    messenger.Register<TRecipient, TMessage>(recipient, (r, m) =>
    {
        if (filter(m))
        {
            handler(r, m);
        }
    });
}
```

Granted, it's not as efficient as a built-in solution for this could be, but supporting this (on top of being a breaking change) would add overhead in all other cases just to support this niche scenario. I don't think it's worth it to implement this at this time.

Thank you for the proposal though! 🙂
