### ISSUE TITLE
Multiple Inheritance Compiler Error CS1721

### ISSUE THREAD

**Issue by SkyGen** [CommunityToolkit/dotnet#618]
### Describe the bug

Hi! 

I would like to use ObservableObject for MVVM projects but I would need to inherit from multiple classes (see error in screenshot).  My projects must inherit from DockPane, as it is a required class for the company I work for. 

I noticed in the doc for error CS1721, it mentions a class may only inherit directly from a single class; however, a class can implement any number of interfaces.  Is there a chance you might add an IObservableObject interface to CommunityToolkit.Mvvm? 

Thanks! 
-Denny

### Steps to reproduce

```text
Allow multiple inheritance via interface. See Expected Behavior example.
```

### Expected behavior

partial class OutputDockPane : DockPane, IObservableObject
{
}

### Screenshots

![ObservableObject Multiple Inheritance](https://user-images.githubusercontent.com/4681646/220510811-190f26c0-f978-48d4-a1d6-ec643bb3592f.png)

### IDE and version

VS 2022

### IDE version

17.5.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.1.0

### Help us help you

No, just wanted to report this

**Comment by TruePluto** [comment]
I don't think It is a good idea to make a `DockPanel` as a `ObservableObject` because it is a class of view, ObservableObject is used as a ViewModel
but if you insist you can try the following code
```cs
[ObservableObject]
partial class OutputDockPane : DockPane
{
}
```

**Comment by SkyGen** [comment]
Thanks @TruePluto

**Comment by Sergio0694** [comment]
This is by design. As mentioned, C# doesn't support multiple inheritance. For situations like these though, you can work around it and get the same functionality by using `[ObservableObject]`, that's exactly what it's made for 🙂
My suggestion would be to have a base type like this:

```csharp
[ObservableObject]
public abstract partial class ObservableDockPane : DockPane
{
}
```

And then just always inherit from this one for your types. This will give you the same features but it will greatly reduce binary size compared to just always using `[ObservableObject]` in each of your types (as this way the code will be shared).

**Comment by SkyGen** [comment]
Much thanks, @Sergio0694. Unfortunatley I can't use the attribute decoration either because DockPane implements INotifyPropertyChanged. I really like the idea of simplified code, though, and I'll keep ObserableObject in mind for other projects. Keep up the great work!
