### ISSUE TITLE
ObservableProperty not generated for WPF application targeting .NET Framework 4.8

### ISSUE THREAD

**Issue by smaugbend** [CommunityToolkit/dotnet#695]
In the [Introduction to the MVVM Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/) Microsoft Learn article (version from January 12, 2023 retrieved on May 12, 2023), it is stated that

> This package targets .NET Standard so it can be used on any app platform: UWP, WinForms, WPF, Xamarin, Uno, and more; and on any runtime: .NET Native, .NET Core, .NET Framework, or Mono. It runs on all of them.

which seems to indicate that this Community Toolkit should work in an application using WPF that targets .NET Framework 4.8.

If this is the case, then I believe there is a bug present in the version 8.2.0 NuGet package.

The issue is that the code for an `ObservableProperty` of an `ObservableObject` (such as in the example in the [ObservablePropertyAttribute Class documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.toolkit.mvvm.componentmodel.observablepropertyattribute)) does not get generated when building a WPF application that targets .NET Framework 4.8.

The attached WpfApp1 Visual Studio 2022 Solution is a minimal reproducible example wherein `Class1` is an `ObservableObject` with an `ObservableProperty` and the `App.OnStartup` method attempts to use the `Class1.Name` property that is supposed to be generated.

Attempting to Build Solution yields

> error CS1061: 'Class1' does not contain a definition for 'Name' and no accessible extension method 'Name' accepting a first argument of type 'Class1' could be found (are you missing a using directive or an assembly reference?)

and is preventing my utilization of this feature.

[WpfApp1.zip](https://github.com/CommunityToolkit/dotnet/files/11467953/WpfApp1.zip)

**Comment by Sergio0694** [comment]
This is expected, as you're using `packages.config` for the NuGet packages. You need to use `<PackageReference>` for the source generators to be loaded correctly. I'll see if I can add a warning for this in the .targets file we ship in the generators 🙂

**Comment by smaugbend** [comment]
@Sergio0694 performing "Migrate packages.config to PackageReference" on the above `WpfApp1` project does seem to make something work, but yields an [MVVM Toolkit error MVVMTK0008](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/errors/mvvmtk0008). It is my understanding that a .NET Framework 4.8 project should only use C# 7.3, so if this Community Toolkit requires at least C# 8.0 then I believe .NET Framework should be removed from the [[Introduction to the MVVM Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/) Microsoft Learn article as a supported runtime.

**Comment by Sergio0694** [comment]
> "performing "Migrate packages.config to PackageReference" on the above `WpfApp1` project does seem to make something work, but yields an [MVVM Toolkit error MVVMTK0008](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/errors/mvvmtk0008)."

That is by design. The fact you got that error means that the source generator is working now, which makes sense.

> "It is my understanding that a .NET Framework 4.8 project should only use C# 7.3, so if this Community Toolkit requires at least C# 8.0 then I believe .NET Framework should be removed from the [Introduction to the MVVM Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/) Microsoft Learn article as a supported runtime."

C# 7.3 is the latest officially supported language version for .NET Framework 4.8, yes. That doesn't mean the MVVM Toolkit doesn't support it though. You're free to either stick to using C# 7.3 and not use the source generators (which is completely supported), or manually bump your language version to a higher version to get access to the source generators (which is technically an unsupported scenario in .NET Framework, so that's up to you). For practical purposes, it works just fine (you can set it all the way up to C# 11 if you wanted), but of course, yes it's technically not supported. If you did want to try bumping that language version, I'd also recommend using [PolySharp](https://github.com/Sergio0694/PolySharp) to help with that.
